### ISSUE TITLE
安装后不显示插件

### ISSUE THREAD

**Issue by wyeeeh** [xinatcg/picgo-plugin-gdrive#1]
型号：Macbook Air M2 Arm环境
安装后日志报错：

```
------Error Stack Begin------
Error: Cannot find module '/Users/ye/Library/Application Support/picgo/node_modules/picgo-plugin-gdrive/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:360:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:573:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:926:27)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Nt.getPlugin (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:43928)
    at Nt.registerPlugin (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:43051)
-------Error Stack End------- 
```

**Comment by xinatcg** [comment]
看上去好像没有安装成功.  你看一下这个目录下的文件:
~/Library/Application Support/picgo/node_modules/picgo-plugin-gdrive/dist

有没有 index.js
